#!/bin/bash
# generated by ll-helper

echo Applying Patch: shell


while read file;do
    echo "Patching $file"
    sed -i -e "s#${LINGLONG_RAW_ID}#${LINGLONG_APP_ID}#g" "$file"
done<<<$(find "$PREFIX" -name "*.sh")