#!/bin/bash
# generated by ll-helper

echo Applying Patch: qt

QT_LIB=$PREFIX/ # $(expr $PREFIX/lib/x86_64-linux-gnu/qt*/ )
QT_SHARE=$(expr $PREFIX/share/qt*/ )

QT_PLATFORM_PATH="${QT_LIB}platforms"
QT_PLUGIN_PATH=$(find ${QT_LIB}plugins/ -name "*.so*" | xargs -I{} dirname "{}" | sort | uniq | paste -sd :)
if [ -n "$QT_PLUGIN_PATH" ]; then
    echo "export QT_PLUGIN_PATH=$QT_PLUGIN_PATH" | tee -a $LINGLONG_COMMAND
    # echo "export EXTRA_QT_PLUGINS=$QT_PLUGIN_PATH" | tee -a $LINGLONG_COMMAND
fi



QTWEBENGINE_RESOURCES_PATH="${QT_SHARE}resources"
if [ -d "$QTWEBENGINE_RESOURCES_PATH" ]; then
    echo QTWEBENGINE_RESOURCES_PATH=$QTWEBENGINE_RESOURCES_PATH
    echo "export QTWEBENGINE_RESOURCES_PATH=$QTWEBENGINE_RESOURCES_PATH" | tee -a $LINGLONG_COMMAND
    ln -svf $QTWEBENGINE_RESOURCES_PATH/* $PREFIX/bin
    ln -svf $QTWEBENGINE_RESOURCES_PATH/* ${QT_LIB}libexec/
fi

QTWEBENGINE_LOCALES_PATH="${QT_SHARE}/translations/qtwebengine_locales"
if [ -d "$QTWEBENGINE_LOCALES_PATH" ]; then
    echo "export QTWEBENGINE_LOCALES_PATH=$QTWEBENGINE_LOCALES_PATH" | tee -a $LINGLONG_COMMAND
    ln -svf $QTWEBENGINE_LOCALES_PATH ${QT_LIB}libexec/
fi

QTWEBENGINEPROCESS_PATH="${QT_LIB}libexec/QtWebEngineProcess"
if [ -e "$QTWEBENGINEPROCESS_PATH" ]; then
    echo "export QTWEBENGINEPROCESS_PATH=$QTWEBENGINEPROCESS_PATH" | tee -a $LINGLONG_COMMAND
fi
QML2_IMPORT_PATH="${QT_LIB}qml"
if [ -e "$QML2_IMPORT_PATH" ]; then
    echo "export QML2_IMPORT_PATH=$QML2_IMPORT_PATH" | tee -a $LINGLONG_COMMAND
fi
