#!/bin/bash
# generated by ll-helper

echo Applying Patch: glib

if ([ -e "$PREFIX/lib/girepository-1.0" ] || [ -e "$PREFIX/lib/x86_64-linux-gnu/girepository-1.0" ]); then
    echo "export GI_TYPELIB_PATH=$PREFIX/lib/girepository-1.0:$PREFIX/lib/x86_64-linux-gnu/girepository-1.0" | tee -a $LINGLONG_COMMAND
fi

for i in $(find "$PREFIX" -name "*.gschema.xml" | xargs -r dirname | uniq); do
    echo Compiling GLib schemas: $i
    glib-compile-schemas $i
    GSETTINGS_SCHEMA_DIR=$GSETTINGS_SCHEMA_DIR:$i
done

if [ -n "$GSETTINGS_SCHEMA_DIR" ]; then
    echo "export GSETTINGS_SCHEMA_DIR=$GSETTINGS_SCHEMA_DIR" | tee -a $LINGLONG_COMMAND
fi
