name: Linglong Builder
run-name: Build Linglong Packages
on:
  push:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    outputs:
      appid-list: ${{ steps.list-appid.outputs.appid }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List target
        id: list-appid
        run: |
          echo "appid=$(node ./list-target.js)" >> $GITHUB_OUTPUT
  build:
    needs: scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        appid: ${{ fromJson(needs.scan.outputs.appid-list) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Target ${{matrix.appid}}
        id: build
        run: |
          echo APPID=${{matrix.appid}}
          export APP_ID=${{matrix.appid}}
          export APP_NAME=$(grep ${{matrix.appid}} list.csv | cut -d, -f2)
          export NEW_APP_ID="${APP_ID}.linyaps"

          yarn install
          bash ./build.sh

          git add ${NEW_APP_ID}
          echo "appid=${NEW_APP_ID}" >> $GITHUB_OUTPUT
          echo "commit=$(git diff --cached --quiet&&echo no||echo yes)" >> $GITHUB_OUTPUT
      - name: Commit
        if: ${{steps.build.outputs.commit == 'yes' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Update ${{matrix.appid}}"
          git push
